---
language: python
python:
  - "2.7"
  - "3.5"
env:
  - ANSIBLE_VERSION=2.3.1.0
cache: bundler
#sudo: false
sudo: required
dist: trusty
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
install:
  # Install Ansible.
  - sudo pip install ansible==$ANSIBLE_VERSION
script:
  # Prepare tests
  - echo localhost > inventory

  # Check syntax
  - ansible-playbook --syntax-check -i inventory test.yml

  # First run
  - ansible-playbook -i inventory test.yml --connection=local --sudo

  # Second run Idempotence test
  - >
    ansible-playbook -i inventory test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - command -v python || exit 1
  - command -v pip || exit 1
  - command -v virtualenv || exit 1

  # Test with python3.4
  - ansible-playbook -i inventory test.yml --connection=local --sudo  -e "python_version=3.4"

  - command -v python3.4 || exit 1
  - command -v pip3.4 || exit 1


python_install: [virtualenv]
#python_bin: ~/virtualenv/python3.5/bin
python_bin: /usr/bin/python
python_pkg_bin: ~/virtualenv/python$TRAVIS_PYTHON_VERSION/bin
