- hosts: all
  tasks:
    - include: 'tasks/main.yml'
  vars:
        python_enabled: yes
        python_ppa: ppa:fkrull/deadsnakes
        python_version: ""
        python_virtualenv: yes
        python_ignore_errors: yes
